<?php
return [
    'service_manager' => [
        'factories' => [
            \torneo\V1\Rest\Torneo\TorneoResource::class => \torneo\V1\Rest\Torneo\TorneoResourceFactory::class,
            \torneo\V1\Rest\Categoria\CategoriaResource::class => \torneo\V1\Rest\Categoria\CategoriaResourceFactory::class,
            \torneo\V1\Rest\Zona\ZonaResource::class => \torneo\V1\Rest\Zona\ZonaResourceFactory::class,
            \torneo\V1\Rest\Equipo\EquipoResource::class => \torneo\V1\Rest\Equipo\EquipoResourceFactory::class,
            \torneo\V1\Rest\Equipozona\EquipozonaResource::class => \torneo\V1\Rest\Equipozona\EquipozonaResourceFactory::class,
            \torneo\V1\Rest\Fixture\FixtureResource::class => \torneo\V1\Rest\Fixture\FixtureResourceFactory::class,
            \torneo\V1\Rest\Torneocompleto\TorneocompletoResource::class => \torneo\V1\Rest\Torneocompleto\TorneocompletoResourceFactory::class,
            \torneo\V1\Rest\Reglas\ReglasResource::class => \torneo\V1\Rest\Reglas\ReglasResourceFactory::class,
            \torneo\V1\Rest\Jugador\JugadorResource::class => \torneo\V1\Rest\Jugador\JugadorResourceFactory::class,
            \torneo\V1\Rest\Fecha\FechaResource::class => \torneo\V1\Rest\Fecha\FechaResourceFactory::class,
            \torneo\V1\Rest\Partidosfecha\PartidosfechaResource::class => \torneo\V1\Rest\Partidosfecha\PartidosfechaResourceFactory::class,
            \torneo\V1\Rest\Goleadores\GoleadoresResource::class => \torneo\V1\Rest\Goleadores\GoleadoresResourceFactory::class,
            \torneo\V1\Rest\Amonestados\AmonestadosResource::class => \torneo\V1\Rest\Amonestados\AmonestadosResourceFactory::class,
            \torneo\V1\Rest\Expulsados\ExpulsadosResource::class => \torneo\V1\Rest\Expulsados\ExpulsadosResourceFactory::class,
            \torneo\V1\Rest\Cargarturnos\CargarturnosResource::class => \torneo\V1\Rest\Cargarturnos\CargarturnosResourceFactory::class,
            \torneo\V1\Rest\Posiciones\PosicionesResource::class => \torneo\V1\Rest\Posiciones\PosicionesResourceFactory::class,
            \torneo\V1\Rest\Turno\TurnoResource::class => \torneo\V1\Rest\Turno\TurnoResourceFactory::class,
            \torneo\V1\Rest\Cancha\CanchaResource::class => \torneo\V1\Rest\Cancha\CanchaResourceFactory::class,
            \torneo\V1\Rest\JugadoresEquipo\JugadoresEquipoResource::class => \torneo\V1\Rest\JugadoresEquipo\JugadoresEquipoResourceFactory::class,
            \torneo\V1\Rest\Posicionesgeneral\PosicionesgeneralResource::class => \torneo\V1\Rest\Posicionesgeneral\PosicionesgeneralResourceFactory::class,
            \torneo\V1\Rest\Cierrafase\CierrafaseResource::class => \torneo\V1\Rest\Cierrafase\CierrafaseResourceFactory::class,
            \torneo\V1\Rest\Sancionados\SancionadosResource::class => \torneo\V1\Rest\Sancionados\SancionadosResourceFactory::class,
            \torneo\V1\Rest\Cierropartido\CierropartidoResource::class => \torneo\V1\Rest\Cierropartido\CierropartidoResourceFactory::class,
            \torneo\V1\Rest\Abropartido\AbropartidoResource::class => \torneo\V1\Rest\Abropartido\AbropartidoResourceFactory::class,
            \torneo\V1\Rest\Vallamenosvencida\VallamenosvencidaResource::class => \torneo\V1\Rest\Vallamenosvencida\VallamenosvencidaResourceFactory::class,
            \torneo\V1\Rest\Encapilla\EncapillaResource::class => \torneo\V1\Rest\Encapilla\EncapillaResourceFactory::class,
            \torneo\V1\Rest\Sancionadosvuelven\SancionadosvuelvenResource::class => \torneo\V1\Rest\Sancionadosvuelven\SancionadosvuelvenResourceFactory::class,
            \torneo\V1\Rest\Reporte\ReporteResource::class => \torneo\V1\Rest\Reporte\ReporteResourceFactory::class,
            \torneo\V1\Rest\Goleadoresporcategoria\GoleadoresporcategoriaResource::class => \torneo\V1\Rest\Goleadoresporcategoria\GoleadoresporcategoriaResourceFactory::class,
            \torneo\V1\Rest\Cargarlistas\CargarlistasResource::class => \torneo\V1\Rest\Cargarlistas\CargarlistasResourceFactory::class,
            \torneo\V1\Rest\Nosepresenta\NosepresentaResource::class => \torneo\V1\Rest\Nosepresenta\NosepresentaResourceFactory::class,
            \torneo\V1\Rest\Limpiobd\LimpiobdResource::class => \torneo\V1\Rest\Limpiobd\LimpiobdResourceFactory::class,
            \torneo\V1\Rest\Quitapuntos\QuitapuntosResource::class => \torneo\V1\Rest\Quitapuntos\QuitapuntosResourceFactory::class,
            \torneo\V1\Rest\Fixturemanual\FixturemanualResource::class => \torneo\V1\Rest\Fixturemanual\FixturemanualResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'torneo.rest.torneo' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/torneo[/:torneo_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Torneo\\Controller',
                    ],
                ],
            ],
            'torneo.rest.categoria' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/categoria[/:categoria_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Categoria\\Controller',
                    ],
                ],
            ],
            'torneo.rest.zona' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/zona[/:zona_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Zona\\Controller',
                    ],
                ],
            ],
            'torneo.rest.equipo' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/equipo[/:equipo_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Equipo\\Controller',
                    ],
                ],
            ],
            'torneo.rest.equipozona' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/equipozona[/:equipozona_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Equipozona\\Controller',
                    ],
                ],
            ],
            'torneo.rest.fixture' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/fixture[/:fixture_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Fixture\\Controller',
                    ],
                ],
            ],
            'torneo.rest.torneocompleto' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/torneocompleto[/:torneocompleto_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Torneocompleto\\Controller',
                    ],
                ],
            ],
            'torneo.rest.reglas' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/reglas[/:reglas_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Reglas\\Controller',
                    ],
                ],
            ],
            'torneo.rest.jugador' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/jugador[/:jugador_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Jugador\\Controller',
                    ],
                ],
            ],
            'torneo.rest.fecha' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/fecha[/:fecha_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Fecha\\Controller',
                    ],
                ],
            ],
            'torneo.rest.partidosfecha' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/partidosfecha[/:partidosfecha_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Partidosfecha\\Controller',
                    ],
                ],
            ],
            'torneo.rest.goleadores' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/goleadores[/:goleadores_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Goleadores\\Controller',
                    ],
                ],
            ],
            'torneo.rest.amonestados' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/amonestados[/:amonestados_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Amonestados\\Controller',
                    ],
                ],
            ],
            'torneo.rest.expulsados' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/expulsados[/:expulsados_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Expulsados\\Controller',
                    ],
                ],
            ],
            'torneo.rest.cargarturnos' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/cargarturnos[/:cargarturnos_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Cargarturnos\\Controller',
                    ],
                ],
            ],
            'torneo.rest.posiciones' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/posiciones[/:posiciones_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Posiciones\\Controller',
                    ],
                ],
            ],
            'torneo.rest.turno' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/turno[/:turno_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Turno\\Controller',
                    ],
                ],
            ],
            'torneo.rest.cancha' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/cancha[/:cancha_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Cancha\\Controller',
                    ],
                ],
            ],
            'torneo.rest.jugadores-equipo' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/jugadores-equipo[/:jugadores_equipo_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\JugadoresEquipo\\Controller',
                    ],
                ],
            ],
            'torneo.rest.posicionesgeneral' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/posicionesgeneral[/:posicionesgeneral_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Posicionesgeneral\\Controller',
                    ],
                ],
            ],
            'torneo.rest.cierrafase' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/cierrafase[/:cierrafase_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Cierrafase\\Controller',
                    ],
                ],
            ],
            'torneo.rest.sancionados' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/sancionados[/:sancionados_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Sancionados\\Controller',
                    ],
                ],
            ],
            'torneo.rest.cierropartido' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/cierropartido[/:cierropartido_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Cierropartido\\Controller',
                    ],
                ],
            ],
            'torneo.rest.abropartido' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/abropartido[/:abropartido_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Abropartido\\Controller',
                    ],
                ],
            ],
            'torneo.rest.vallamenosvencida' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/vallamenosvencida[/:vallamenosvencida_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Vallamenosvencida\\Controller',
                    ],
                ],
            ],
            'torneo.rest.encapilla' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/encapilla[/:encapilla_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Encapilla\\Controller',
                    ],
                ],
            ],
            'torneo.rest.sancionadosvuelven' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/sancionadosvuelven[/:sancionadosvuelven_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Sancionadosvuelven\\Controller',
                    ],
                ],
            ],
            'torneo.rest.reporte' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/reporte[/:reporte_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Reporte\\Controller',
                    ],
                ],
            ],
            'torneo.rest.goleadoresporcategoria' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/goleadoresporcategoria[/:goleadoresporcategoria_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Goleadoresporcategoria\\Controller',
                    ],
                ],
            ],
            'torneo.rest.cargarlistas' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/cargarlistas[/:cargarlistas_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Cargarlistas\\Controller',
                    ],
                ],
            ],
            'torneo.rest.nosepresenta' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/nosepresenta[/:nosepresenta_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Nosepresenta\\Controller',
                    ],
                ],
            ],
            'torneo.rest.limpiobd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/limpiobd[/:limpiobd_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Limpiobd\\Controller',
                    ],
                ],
            ],
            'torneo.rest.quitapuntos' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/quitapuntos[/:quitapuntos_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Quitapuntos\\Controller',
                    ],
                ],
            ],
            'torneo.rest.fixturemanual' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/fixturemanual[/:fixturemanual_id]',
                    'defaults' => [
                        'controller' => 'torneo\\V1\\Rest\\Fixturemanual\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'torneo.rest.torneo',
            1 => 'torneo.rest.categoria',
            2 => 'torneo.rest.zona',
            3 => 'torneo.rest.equipo',
            4 => 'torneo.rest.equipozona',
            5 => 'torneo.rest.fixture',
            6 => 'torneo.rest.torneocompleto',
            7 => 'torneo.rest.reglas',
            8 => 'torneo.rest.jugador',
            9 => 'torneo.rest.fecha',
            10 => 'torneo.rest.partidosfecha',
            11 => 'torneo.rest.goleadores',
            12 => 'torneo.rest.amonestados',
            13 => 'torneo.rest.expulsados',
            14 => 'torneo.rest.cargarturnos',
            15 => 'torneo.rest.posiciones',
            16 => 'torneo.rest.turno',
            17 => 'torneo.rest.cancha',
            18 => 'torneo.rest.jugadores-equipo',
            20 => 'torneo.rest.posicionesgeneral',
            22 => 'torneo.rest.cierrafase',
            23 => 'torneo.rest.sancionados',
            24 => 'torneo.rest.cierropartido',
            25 => 'torneo.rest.abropartido',
            26 => 'torneo.rest.vallamenosvencida',
            27 => 'torneo.rest.encapilla',
            28 => 'torneo.rest.sancionadosvuelven',
            31 => 'torneo.rest.reporte',
            32 => 'torneo.rest.goleadoresporcategoria',
            33 => 'torneo.rest.cargarlistas',
            34 => 'torneo.rest.nosepresenta',
            35 => 'torneo.rest.limpiobd',
            36 => 'torneo.rest.quitapuntos',
            37 => 'torneo.rest.fixturemanual',
        ],
    ],
    'zf-rest' => [
        'torneo\\V1\\Rest\\Torneo\\Controller' => [
            'listener' => \torneo\V1\Rest\Torneo\TorneoResource::class,
            'route_name' => 'torneo.rest.torneo',
            'route_identifier_name' => 'torneo_id',
            'collection_name' => 'torneo',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Torneo\TorneoEntity::class,
            'collection_class' => \torneo\V1\Rest\Torneo\TorneoCollection::class,
            'service_name' => 'torneo',
        ],
        'torneo\\V1\\Rest\\Categoria\\Controller' => [
            'listener' => \torneo\V1\Rest\Categoria\CategoriaResource::class,
            'route_name' => 'torneo.rest.categoria',
            'route_identifier_name' => 'categoria_id',
            'collection_name' => 'categoria',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Categoria\CategoriaEntity::class,
            'collection_class' => \torneo\V1\Rest\Categoria\CategoriaCollection::class,
            'service_name' => 'categoria',
        ],
        'torneo\\V1\\Rest\\Zona\\Controller' => [
            'listener' => \torneo\V1\Rest\Zona\ZonaResource::class,
            'route_name' => 'torneo.rest.zona',
            'route_identifier_name' => 'zona_id',
            'collection_name' => 'zona',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Zona\ZonaEntity::class,
            'collection_class' => \torneo\V1\Rest\Zona\ZonaCollection::class,
            'service_name' => 'zona',
        ],
        'torneo\\V1\\Rest\\Equipo\\Controller' => [
            'listener' => \torneo\V1\Rest\Equipo\EquipoResource::class,
            'route_name' => 'torneo.rest.equipo',
            'route_identifier_name' => 'equipo_id',
            'collection_name' => 'equipo',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Equipo\EquipoEntity::class,
            'collection_class' => \torneo\V1\Rest\Equipo\EquipoCollection::class,
            'service_name' => 'equipo',
        ],
        'torneo\\V1\\Rest\\Equipozona\\Controller' => [
            'listener' => \torneo\V1\Rest\Equipozona\EquipozonaResource::class,
            'route_name' => 'torneo.rest.equipozona',
            'route_identifier_name' => 'equipozona_id',
            'collection_name' => 'equipozona',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Equipozona\EquipozonaEntity::class,
            'collection_class' => \torneo\V1\Rest\Equipozona\EquipozonaCollection::class,
            'service_name' => 'equipozona',
        ],
        'torneo\\V1\\Rest\\Fixture\\Controller' => [
            'listener' => \torneo\V1\Rest\Fixture\FixtureResource::class,
            'route_name' => 'torneo.rest.fixture',
            'route_identifier_name' => 'fixture_id',
            'collection_name' => 'fixture',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Fixture\FixtureEntity::class,
            'collection_class' => \torneo\V1\Rest\Fixture\FixtureCollection::class,
            'service_name' => 'fixture',
        ],
        'torneo\\V1\\Rest\\Torneocompleto\\Controller' => [
            'listener' => \torneo\V1\Rest\Torneocompleto\TorneocompletoResource::class,
            'route_name' => 'torneo.rest.torneocompleto',
            'route_identifier_name' => 'torneocompleto_id',
            'collection_name' => 'torneocompleto',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Torneocompleto\TorneocompletoEntity::class,
            'collection_class' => \torneo\V1\Rest\Torneocompleto\TorneocompletoCollection::class,
            'service_name' => 'torneocompleto',
        ],
        'torneo\\V1\\Rest\\Reglas\\Controller' => [
            'listener' => \torneo\V1\Rest\Reglas\ReglasResource::class,
            'route_name' => 'torneo.rest.reglas',
            'route_identifier_name' => 'reglas_id',
            'collection_name' => 'reglas',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Reglas\ReglasEntity::class,
            'collection_class' => \torneo\V1\Rest\Reglas\ReglasCollection::class,
            'service_name' => 'reglas',
        ],
        'torneo\\V1\\Rest\\Jugador\\Controller' => [
            'listener' => \torneo\V1\Rest\Jugador\JugadorResource::class,
            'route_name' => 'torneo.rest.jugador',
            'route_identifier_name' => 'jugador_id',
            'collection_name' => 'jugador',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Jugador\JugadorEntity::class,
            'collection_class' => \torneo\V1\Rest\Jugador\JugadorCollection::class,
            'service_name' => 'jugador',
        ],
        'torneo\\V1\\Rest\\Fecha\\Controller' => [
            'listener' => \torneo\V1\Rest\Fecha\FechaResource::class,
            'route_name' => 'torneo.rest.fecha',
            'route_identifier_name' => 'fecha_id',
            'collection_name' => 'fecha',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Fecha\FechaEntity::class,
            'collection_class' => \torneo\V1\Rest\Fecha\FechaCollection::class,
            'service_name' => 'fecha',
        ],
        'torneo\\V1\\Rest\\Partidosfecha\\Controller' => [
            'listener' => \torneo\V1\Rest\Partidosfecha\PartidosfechaResource::class,
            'route_name' => 'torneo.rest.partidosfecha',
            'route_identifier_name' => 'partidosfecha_id',
            'collection_name' => 'partidosfecha',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Partidosfecha\PartidosfechaEntity::class,
            'collection_class' => \torneo\V1\Rest\Partidosfecha\PartidosfechaCollection::class,
            'service_name' => 'partidosfecha',
        ],
        'torneo\\V1\\Rest\\Goleadores\\Controller' => [
            'listener' => \torneo\V1\Rest\Goleadores\GoleadoresResource::class,
            'route_name' => 'torneo.rest.goleadores',
            'route_identifier_name' => 'goleadores_id',
            'collection_name' => 'goleadores',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Goleadores\GoleadoresEntity::class,
            'collection_class' => \torneo\V1\Rest\Goleadores\GoleadoresCollection::class,
            'service_name' => 'goleadores',
        ],
        'torneo\\V1\\Rest\\Amonestados\\Controller' => [
            'listener' => \torneo\V1\Rest\Amonestados\AmonestadosResource::class,
            'route_name' => 'torneo.rest.amonestados',
            'route_identifier_name' => 'amonestados_id',
            'collection_name' => 'amonestados',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Amonestados\AmonestadosEntity::class,
            'collection_class' => \torneo\V1\Rest\Amonestados\AmonestadosCollection::class,
            'service_name' => 'amonestados',
        ],
        'torneo\\V1\\Rest\\Expulsados\\Controller' => [
            'listener' => \torneo\V1\Rest\Expulsados\ExpulsadosResource::class,
            'route_name' => 'torneo.rest.expulsados',
            'route_identifier_name' => 'expulsados_id',
            'collection_name' => 'expulsados',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Expulsados\ExpulsadosEntity::class,
            'collection_class' => \torneo\V1\Rest\Expulsados\ExpulsadosCollection::class,
            'service_name' => 'expulsados',
        ],
        'torneo\\V1\\Rest\\Cargarturnos\\Controller' => [
            'listener' => \torneo\V1\Rest\Cargarturnos\CargarturnosResource::class,
            'route_name' => 'torneo.rest.cargarturnos',
            'route_identifier_name' => 'cargarturnos_id',
            'collection_name' => 'cargarturnos',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Cargarturnos\CargarturnosEntity::class,
            'collection_class' => \torneo\V1\Rest\Cargarturnos\CargarturnosCollection::class,
            'service_name' => 'cargarturnos',
        ],
        'torneo\\V1\\Rest\\Posiciones\\Controller' => [
            'listener' => \torneo\V1\Rest\Posiciones\PosicionesResource::class,
            'route_name' => 'torneo.rest.posiciones',
            'route_identifier_name' => 'posiciones_id',
            'collection_name' => 'posiciones',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Posiciones\PosicionesEntity::class,
            'collection_class' => \torneo\V1\Rest\Posiciones\PosicionesCollection::class,
            'service_name' => 'posiciones',
        ],
        'torneo\\V1\\Rest\\Turno\\Controller' => [
            'listener' => \torneo\V1\Rest\Turno\TurnoResource::class,
            'route_name' => 'torneo.rest.turno',
            'route_identifier_name' => 'turno_id',
            'collection_name' => 'turno',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Turno\TurnoEntity::class,
            'collection_class' => \torneo\V1\Rest\Turno\TurnoCollection::class,
            'service_name' => 'turno',
        ],
        'torneo\\V1\\Rest\\Cancha\\Controller' => [
            'listener' => \torneo\V1\Rest\Cancha\CanchaResource::class,
            'route_name' => 'torneo.rest.cancha',
            'route_identifier_name' => 'cancha_id',
            'collection_name' => 'cancha',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Cancha\CanchaEntity::class,
            'collection_class' => \torneo\V1\Rest\Cancha\CanchaCollection::class,
            'service_name' => 'cancha',
        ],
        'torneo\\V1\\Rest\\JugadoresEquipo\\Controller' => [
            'listener' => \torneo\V1\Rest\JugadoresEquipo\JugadoresEquipoResource::class,
            'route_name' => 'torneo.rest.jugadores-equipo',
            'route_identifier_name' => 'jugadores_equipo_id',
            'collection_name' => 'jugadores_equipo',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\JugadoresEquipo\JugadoresEquipoEntity::class,
            'collection_class' => \torneo\V1\Rest\JugadoresEquipo\JugadoresEquipoCollection::class,
            'service_name' => 'jugadoresEquipo',
        ],
        'torneo\\V1\\Rest\\Posicionesgeneral\\Controller' => [
            'listener' => \torneo\V1\Rest\Posicionesgeneral\PosicionesgeneralResource::class,
            'route_name' => 'torneo.rest.posicionesgeneral',
            'route_identifier_name' => 'posicionesgeneral_id',
            'collection_name' => 'posicionesgeneral',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Posicionesgeneral\PosicionesgeneralEntity::class,
            'collection_class' => \torneo\V1\Rest\Posicionesgeneral\PosicionesgeneralCollection::class,
            'service_name' => 'posicionesgeneral',
        ],
        'torneo\\V1\\Rest\\Cierrafase\\Controller' => [
            'listener' => \torneo\V1\Rest\Cierrafase\CierrafaseResource::class,
            'route_name' => 'torneo.rest.cierrafase',
            'route_identifier_name' => 'cierrafase_id',
            'collection_name' => 'cierrafase',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Cierrafase\CierrafaseEntity::class,
            'collection_class' => \torneo\V1\Rest\Cierrafase\CierrafaseCollection::class,
            'service_name' => 'cierrafase',
        ],
        'torneo\\V1\\Rest\\Sancionados\\Controller' => [
            'listener' => \torneo\V1\Rest\Sancionados\SancionadosResource::class,
            'route_name' => 'torneo.rest.sancionados',
            'route_identifier_name' => 'sancionados_id',
            'collection_name' => 'sancionados',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Sancionados\SancionadosEntity::class,
            'collection_class' => \torneo\V1\Rest\Sancionados\SancionadosCollection::class,
            'service_name' => 'sancionados',
        ],
        'torneo\\V1\\Rest\\Cierropartido\\Controller' => [
            'listener' => \torneo\V1\Rest\Cierropartido\CierropartidoResource::class,
            'route_name' => 'torneo.rest.cierropartido',
            'route_identifier_name' => 'cierropartido_id',
            'collection_name' => 'cierropartido',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Cierropartido\CierropartidoEntity::class,
            'collection_class' => \torneo\V1\Rest\Cierropartido\CierropartidoCollection::class,
            'service_name' => 'cierropartido',
        ],
        'torneo\\V1\\Rest\\Abropartido\\Controller' => [
            'listener' => \torneo\V1\Rest\Abropartido\AbropartidoResource::class,
            'route_name' => 'torneo.rest.abropartido',
            'route_identifier_name' => 'abropartido_id',
            'collection_name' => 'abropartido',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Abropartido\AbropartidoEntity::class,
            'collection_class' => \torneo\V1\Rest\Abropartido\AbropartidoCollection::class,
            'service_name' => 'abropartido',
        ],
        'torneo\\V1\\Rest\\Vallamenosvencida\\Controller' => [
            'listener' => \torneo\V1\Rest\Vallamenosvencida\VallamenosvencidaResource::class,
            'route_name' => 'torneo.rest.vallamenosvencida',
            'route_identifier_name' => 'vallamenosvencida_id',
            'collection_name' => 'vallamenosvencida',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Vallamenosvencida\VallamenosvencidaEntity::class,
            'collection_class' => \torneo\V1\Rest\Vallamenosvencida\VallamenosvencidaCollection::class,
            'service_name' => 'vallamenosvencida',
        ],
        'torneo\\V1\\Rest\\Encapilla\\Controller' => [
            'listener' => \torneo\V1\Rest\Encapilla\EncapillaResource::class,
            'route_name' => 'torneo.rest.encapilla',
            'route_identifier_name' => 'encapilla_id',
            'collection_name' => 'encapilla',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Encapilla\EncapillaEntity::class,
            'collection_class' => \torneo\V1\Rest\Encapilla\EncapillaCollection::class,
            'service_name' => 'encapilla',
        ],
        'torneo\\V1\\Rest\\Sancionadosvuelven\\Controller' => [
            'listener' => \torneo\V1\Rest\Sancionadosvuelven\SancionadosvuelvenResource::class,
            'route_name' => 'torneo.rest.sancionadosvuelven',
            'route_identifier_name' => 'sancionadosvuelven_id',
            'collection_name' => 'sancionadosvuelven',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Sancionadosvuelven\SancionadosvuelvenEntity::class,
            'collection_class' => \torneo\V1\Rest\Sancionadosvuelven\SancionadosvuelvenCollection::class,
            'service_name' => 'sancionadosvuelven',
        ],
        'torneo\\V1\\Rest\\Reporte\\Controller' => [
            'listener' => \torneo\V1\Rest\Reporte\ReporteResource::class,
            'route_name' => 'torneo.rest.reporte',
            'route_identifier_name' => 'reporte_id',
            'collection_name' => 'reporte',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Reporte\ReporteEntity::class,
            'collection_class' => \torneo\V1\Rest\Reporte\ReporteCollection::class,
            'service_name' => 'reporte',
        ],
        'torneo\\V1\\Rest\\Goleadoresporcategoria\\Controller' => [
            'listener' => \torneo\V1\Rest\Goleadoresporcategoria\GoleadoresporcategoriaResource::class,
            'route_name' => 'torneo.rest.goleadoresporcategoria',
            'route_identifier_name' => 'goleadoresporcategoria_id',
            'collection_name' => 'goleadoresporcategoria',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Goleadoresporcategoria\GoleadoresporcategoriaEntity::class,
            'collection_class' => \torneo\V1\Rest\Goleadoresporcategoria\GoleadoresporcategoriaCollection::class,
            'service_name' => 'goleadoresporcategoria',
        ],
        'torneo\\V1\\Rest\\Cargarlistas\\Controller' => [
            'listener' => \torneo\V1\Rest\Cargarlistas\CargarlistasResource::class,
            'route_name' => 'torneo.rest.cargarlistas',
            'route_identifier_name' => 'cargarlistas_id',
            'collection_name' => 'cargarlistas',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Cargarlistas\CargarlistasEntity::class,
            'collection_class' => \torneo\V1\Rest\Cargarlistas\CargarlistasCollection::class,
            'service_name' => 'cargarlistas',
        ],
        'torneo\\V1\\Rest\\Nosepresenta\\Controller' => [
            'listener' => \torneo\V1\Rest\Nosepresenta\NosepresentaResource::class,
            'route_name' => 'torneo.rest.nosepresenta',
            'route_identifier_name' => 'nosepresenta_id',
            'collection_name' => 'nosepresenta',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Nosepresenta\NosepresentaEntity::class,
            'collection_class' => \torneo\V1\Rest\Nosepresenta\NosepresentaCollection::class,
            'service_name' => 'nosepresenta',
        ],
        'torneo\\V1\\Rest\\Limpiobd\\Controller' => [
            'listener' => \torneo\V1\Rest\Limpiobd\LimpiobdResource::class,
            'route_name' => 'torneo.rest.limpiobd',
            'route_identifier_name' => 'limpiobd_id',
            'collection_name' => 'limpiobd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Limpiobd\LimpiobdEntity::class,
            'collection_class' => \torneo\V1\Rest\Limpiobd\LimpiobdCollection::class,
            'service_name' => 'limpiobd',
        ],
        'torneo\\V1\\Rest\\Quitapuntos\\Controller' => [
            'listener' => \torneo\V1\Rest\Quitapuntos\QuitapuntosResource::class,
            'route_name' => 'torneo.rest.quitapuntos',
            'route_identifier_name' => 'quitapuntos_id',
            'collection_name' => 'quitapuntos',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Quitapuntos\QuitapuntosEntity::class,
            'collection_class' => \torneo\V1\Rest\Quitapuntos\QuitapuntosCollection::class,
            'service_name' => 'quitapuntos',
        ],
        'torneo\\V1\\Rest\\Fixturemanual\\Controller' => [
            'listener' => \torneo\V1\Rest\Fixturemanual\FixturemanualResource::class,
            'route_name' => 'torneo.rest.fixturemanual',
            'route_identifier_name' => 'fixturemanual_id',
            'collection_name' => 'fixturemanual',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \torneo\V1\Rest\Fixturemanual\FixturemanualEntity::class,
            'collection_class' => \torneo\V1\Rest\Fixturemanual\FixturemanualCollection::class,
            'service_name' => 'fixturemanual',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'torneo\\V1\\Rest\\Torneo\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Categoria\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Zona\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Equipo\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Equipozona\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Fixture\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Torneocompleto\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Reglas\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Jugador\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Fecha\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Partidosfecha\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Goleadores\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Amonestados\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Expulsados\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Cargarturnos\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Posiciones\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Turno\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Cancha\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\JugadoresEquipo\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Posicionesgeneral\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Cierrafase\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Sancionados\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Cierropartido\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Abropartido\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Vallamenosvencida\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Encapilla\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Sancionadosvuelven\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Reporte\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Goleadoresporcategoria\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Cargarlistas\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Nosepresenta\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Limpiobd\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Quitapuntos\\Controller' => 'HalJson',
            'torneo\\V1\\Rest\\Fixturemanual\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'torneo\\V1\\Rest\\Torneo\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Categoria\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Zona\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Equipo\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Equipozona\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Fixture\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Torneocompleto\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Reglas\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Jugador\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Fecha\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Partidosfecha\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Goleadores\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
                3 => 'application/x-www-form-urlencoded',
            ],
            'torneo\\V1\\Rest\\Amonestados\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Expulsados\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cargarturnos\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Posiciones\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Turno\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cancha\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\JugadoresEquipo\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Posicionesgeneral\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cierrafase\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Sancionados\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cierropartido\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Abropartido\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Vallamenosvencida\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Encapilla\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Sancionadosvuelven\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Reporte\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Goleadoresporcategoria\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cargarlistas\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Nosepresenta\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
                3 => 'application/x-www-form-urlencoded',
            ],
            'torneo\\V1\\Rest\\Limpiobd\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Quitapuntos\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Fixturemanual\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'torneo\\V1\\Rest\\Torneo\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Categoria\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Zona\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Equipo\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Equipozona\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Fixture\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Torneocompleto\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Reglas\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Jugador\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Fecha\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Partidosfecha\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Goleadores\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
                2 => 'application/x-www-form-urlencoded',
            ],
            'torneo\\V1\\Rest\\Amonestados\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Expulsados\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cargarturnos\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Posiciones\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Turno\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cancha\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\JugadoresEquipo\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Posicionesgeneral\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cierrafase\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Sancionados\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cierropartido\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Abropartido\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Vallamenosvencida\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Encapilla\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Sancionadosvuelven\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Reporte\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Goleadoresporcategoria\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Cargarlistas\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Nosepresenta\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
                2 => 'application/x-www-form-urlencoded',
            ],
            'torneo\\V1\\Rest\\Limpiobd\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Quitapuntos\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
            'torneo\\V1\\Rest\\Fixturemanual\\Controller' => [
                0 => 'application/vnd.torneo.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \torneo\V1\Rest\Torneo\TorneoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.torneo',
                'route_identifier_name' => 'torneo_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Torneo\TorneoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.torneo',
                'route_identifier_name' => 'torneo_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Categoria\CategoriaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.categoria',
                'route_identifier_name' => 'categoria_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Categoria\CategoriaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.categoria',
                'route_identifier_name' => 'categoria_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Zona\ZonaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.zona',
                'route_identifier_name' => 'zona_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Zona\ZonaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.zona',
                'route_identifier_name' => 'zona_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Equipo\EquipoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.equipo',
                'route_identifier_name' => 'equipo_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Equipo\EquipoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.equipo',
                'route_identifier_name' => 'equipo_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Equipozona\EquipozonaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.equipozona',
                'route_identifier_name' => 'equipozona_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Equipozona\EquipozonaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.equipozona',
                'route_identifier_name' => 'equipozona_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Fixture\FixtureEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.fixture',
                'route_identifier_name' => 'fixture_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Fixture\FixtureCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.fixture',
                'route_identifier_name' => 'fixture_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Torneocompleto\TorneocompletoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.torneocompleto',
                'route_identifier_name' => 'torneocompleto_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Torneocompleto\TorneocompletoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.torneocompleto',
                'route_identifier_name' => 'torneocompleto_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Reglas\ReglasEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.reglas',
                'route_identifier_name' => 'reglas_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Reglas\ReglasCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.reglas',
                'route_identifier_name' => 'reglas_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Jugador\JugadorEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.jugador',
                'route_identifier_name' => 'jugador_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Jugador\JugadorCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.jugador',
                'route_identifier_name' => 'jugador_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Fecha\FechaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.fecha',
                'route_identifier_name' => 'fecha_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Fecha\FechaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.fecha',
                'route_identifier_name' => 'fecha_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Partidosfecha\PartidosfechaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.partidosfecha',
                'route_identifier_name' => 'partidosfecha_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Partidosfecha\PartidosfechaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.partidosfecha',
                'route_identifier_name' => 'partidosfecha_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Goleadores\GoleadoresEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.goleadores',
                'route_identifier_name' => 'goleadores_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Goleadores\GoleadoresCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.goleadores',
                'route_identifier_name' => 'goleadores_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Amonestados\AmonestadosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.amonestados',
                'route_identifier_name' => 'amonestados_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Amonestados\AmonestadosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.amonestados',
                'route_identifier_name' => 'amonestados_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Expulsados\ExpulsadosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.expulsados',
                'route_identifier_name' => 'expulsados_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Expulsados\ExpulsadosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.expulsados',
                'route_identifier_name' => 'expulsados_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Cargarturnos\CargarturnosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cargarturnos',
                'route_identifier_name' => 'cargarturnos_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Cargarturnos\CargarturnosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cargarturnos',
                'route_identifier_name' => 'cargarturnos_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Posiciones\PosicionesEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.posiciones',
                'route_identifier_name' => 'posiciones_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Posiciones\PosicionesCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.posiciones',
                'route_identifier_name' => 'posiciones_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Turno\TurnoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.turno',
                'route_identifier_name' => 'turno_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Turno\TurnoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.turno',
                'route_identifier_name' => 'turno_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Cancha\CanchaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cancha',
                'route_identifier_name' => 'cancha_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Cancha\CanchaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cancha',
                'route_identifier_name' => 'cancha_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\JugadoresEquipo\JugadoresEquipoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.jugadores-equipo',
                'route_identifier_name' => 'jugadores_equipo_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\JugadoresEquipo\JugadoresEquipoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.jugadores-equipo',
                'route_identifier_name' => 'jugadores_equipo_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Posicionesgeneral\PosicionesgeneralEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.posicionesgeneral',
                'route_identifier_name' => 'posicionesgeneral_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Posicionesgeneral\PosicionesgeneralCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.posicionesgeneral',
                'route_identifier_name' => 'posicionesgeneral_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Cierrafase\CierrafaseEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cierrafase',
                'route_identifier_name' => 'cierrafase_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Cierrafase\CierrafaseCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cierrafase',
                'route_identifier_name' => 'cierrafase_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Sancionados\SancionadosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.sancionados',
                'route_identifier_name' => 'sancionados_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Sancionados\SancionadosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.sancionados',
                'route_identifier_name' => 'sancionados_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Cierropartido\CierropartidoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cierropartido',
                'route_identifier_name' => 'cierropartido_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Cierropartido\CierropartidoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cierropartido',
                'route_identifier_name' => 'cierropartido_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Abropartido\AbropartidoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.abropartido',
                'route_identifier_name' => 'abropartido_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Abropartido\AbropartidoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.abropartido',
                'route_identifier_name' => 'abropartido_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Vallamenosvencida\VallamenosvencidaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.vallamenosvencida',
                'route_identifier_name' => 'vallamenosvencida_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Vallamenosvencida\VallamenosvencidaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.vallamenosvencida',
                'route_identifier_name' => 'vallamenosvencida_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Encapilla\EncapillaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.encapilla',
                'route_identifier_name' => 'encapilla_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Encapilla\EncapillaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.encapilla',
                'route_identifier_name' => 'encapilla_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Sancionadosvuelven\SancionadosvuelvenEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.sancionadosvuelven',
                'route_identifier_name' => 'sancionadosvuelven_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Sancionadosvuelven\SancionadosvuelvenCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.sancionadosvuelven',
                'route_identifier_name' => 'sancionadosvuelven_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Reporte\ReporteEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.reporte',
                'route_identifier_name' => 'reporte_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Reporte\ReporteCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.reporte',
                'route_identifier_name' => 'reporte_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Goleadoresporcategoria\GoleadoresporcategoriaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.goleadoresporcategoria',
                'route_identifier_name' => 'goleadoresporcategoria_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Goleadoresporcategoria\GoleadoresporcategoriaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.goleadoresporcategoria',
                'route_identifier_name' => 'goleadoresporcategoria_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Cargarlistas\CargarlistasEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cargarlistas',
                'route_identifier_name' => 'cargarlistas_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Cargarlistas\CargarlistasCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.cargarlistas',
                'route_identifier_name' => 'cargarlistas_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Nosepresenta\NosepresentaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.nosepresenta',
                'route_identifier_name' => 'nosepresenta_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Nosepresenta\NosepresentaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.nosepresenta',
                'route_identifier_name' => 'nosepresenta_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Limpiobd\LimpiobdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.limpiobd',
                'route_identifier_name' => 'limpiobd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Limpiobd\LimpiobdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.limpiobd',
                'route_identifier_name' => 'limpiobd_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Quitapuntos\QuitapuntosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.quitapuntos',
                'route_identifier_name' => 'quitapuntos_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Quitapuntos\QuitapuntosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.quitapuntos',
                'route_identifier_name' => 'quitapuntos_id',
                'is_collection' => true,
            ],
            \torneo\V1\Rest\Fixturemanual\FixturemanualEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.fixturemanual',
                'route_identifier_name' => 'fixturemanual_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \torneo\V1\Rest\Fixturemanual\FixturemanualCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'torneo.rest.fixturemanual',
                'route_identifier_name' => 'fixturemanual_id',
                'is_collection' => true,
            ],
        ],
    ],
    'zf-mvc-auth' => [
        'authorization' => [
            'torneo\\V1\\Rest\\Torneo\\Controller' => [
                'collection' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
                'entity' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
            ],
        ],
    ],
];
